{% set name = "auto-all" %}
{% set version = "1.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/auto-all-{{ version }}.tar.gz
  sha256: 495ad1fe74972207837f7ae40ef8ee581da92e63c57f6cc496b2869c05aa9b12

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - m2r
    - pip
    - pygments
    - python {{ python_min }}
    - restructuredtext_lint
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - auto_all
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jongracecox/auto-all
  summary: Automatically manage __all__ variable in Python packages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
